export {
  CARD_SCHEMA_VERSION,
  CARD_ID_PATTERN,
  cardIdSchema,
  COLOR_IDS,
  colorIdSchema,
  colorIdentitySchema,
  CARD_TYPES,
  cardTypeSchema,
  ROLES,
  roleSchema,
  POWER_CLASSES,
  powerClassSchema,
  KEYWORD_IDS,
  keywordIdSchema,
  tagSchema,
  ZONE_IDS,
  zoneIdSchema,
  TARGETABLE_ZONE_IDS,
  DECKABLE_CARD_TYPES,
  REACTION_WINDOWS,
  reactionWindowSchema,
  type ReactionWindow,
  SET_STATUSES,
  setStatusSchema,
  STRICT_SET_STATUSES,
  type SetStatus,
  type CardId,
  type ColorId,
  type CardType,
  type Role,
  type PowerClass,
  type KeywordId,
  type Tag,
  type ZoneId,
} from './schema/primitives.js';

export {
  cardFilterSchema,
  controllerSchema,
  durationSchema,
  numericRangeSchema,
  playerSelectorSchema,
  selectionModeSchema,
  targetSelectorSchema,
  targetDefinitionSchema,
  targetCountSchema,
  entityTarget,
  targetsPlayers,
  CONTROLLERS,
  DURATIONS,
  PLAYER_SELECTORS,
  SELECTION_MODES,
  type CardFilter,
  type CardFilterAlternative,
  type Controller,
  type Duration,
  type NumericRange,
  type PlayerSelector,
  type SelectionMode,
  type TargetCount,
  type TargetDefinition,
  type TargetDefinitionInput,
  type TargetSelector,
} from './schema/target.js';

export {
  effectDefinitionSchema,
  abilityDefinitionSchema,
  abilityCostSchema,
  additionalCostSchema,
  activatedAbilityDefinitionSchema,
  abilityUsageLimitSchema,
  continuousScopeSchema,
  staticAbilityDefinitionSchema,
  triggerIdSchema,
  triggerScopeSchema,
  triggerLimitSchema,
  ABILITY_USAGE_LIMITS,
  CARD_SCOPED_TRIGGERS,
  EFFECT_TYPES,
  TRIGGER_IDS,
  TRIGGER_LIMITS,
  type AbilityCost,
  type AdditionalCost,
  type AbilityDefinition,
  type ActivatedAbilityDefinition,
  type AbilityUsageLimit,
  type ContinuousScope,
  type EffectDefinition,
  type EffectType,
  type EntityTarget,
  type StaticAbilityDefinition,
  type TriggerId,
  type TriggerLimit,
  type TriggerScope,
} from './schema/effect.js';

export {
  conditionSchema,
  countQuerySchema,
  comparisonSchema,
  countSubjectSchema,
  sourceStateSchema,
  valueExpressionSchema,
  signedValueExpressionSchema,
  isFixedValue,
  COMPARISONS,
  COUNT_SUBJECTS,
  SOURCE_STATES,
  type Comparison,
  type ConditionDefinition,
  type CountQuery,
  type CountSubject,
  type SignedValueExpression,
  type SourceState,
  type ValueExpression,
} from './schema/condition.js';

export {
  FORMAT_SCHEMA_VERSION,
  formatIdSchema,
  deckConstructionSchema,
  playFormatSchema,
  type DeckConstruction,
  type PlayFormat,
  type PlayFormatInput,
} from './schema/format.js';

export {
  cardDefinitionSchema,
  cardSetSchema,
  setIdSchema,
  cardPatchBodySchema,
  reactionTimingSchema,
  applyCardPatch,
  PATCHABLE_CARD_FIELDS,
  type CardDefinition,
  type CardDefinitionInput,
  type CardPatchBody,
  type CardSet,
  type CardSetInput,
  type CardText,
  type PatchableCardField,
  type ReactionTiming,
} from './schema/card.js';

export { CardDatabase } from './database.js';
export { loadCardSets, zodIssuesToIssues, type LoadedCardData } from './loader.js';
export { migrateCardSet, canMigrateCardSet } from './migrate.js';
export {
  PRECON_SCHEMA_VERSION,
  preconDefinitionSchema,
  type PreconDefinition,
} from './schema/precon.js';

export {
  BUNDLED_CARD_SETS,
  BUNDLED_FORMATS,
  BUNDLED_PRECONS,
  bundledPrecon,
  DEFAULT_FORMAT_ID,
  bundledFormat,
  formatCardPool,
  formatDatabase,
  loadBundledCardData,
} from './default-set.js';
export { compareCards, isColorIdentityLegal, matchesQuery, type CardQuery } from './query.js';
export {
  artworkSources,
  cardArtUrl,
  fallbackArtUrl,
  nextArtworkSource,
  CARD_ART_ASPECT_RATIO,
  CARD_ART_WIDTH_PX,
  CARD_ART_HEIGHT_PX,
  DEFAULT_ART_BASE_URL,
  DEFAULT_FALLBACK_ART_URL,
  type ArtworkResolverOptions,
} from './artwork.js';
export { lintDisplayText } from './display-text.js';
export {
  KEYWORD_REGISTRY,
  KEYWORD_LIST,
  KEYWORD_CATEGORIES,
  KEYWORD_REGISTRY_SCHEMA_VERSION,
  IMPLEMENTED_KEYWORDS,
  UNIMPLEMENTED_KEYWORDS,
  keywordCategorySchema,
  keywordDefinition,
  keywordDefinitionSchema,
  type KeywordCategory,
  type KeywordDefinition,
} from './keywords.js';
export {
  COLOR_INFO,
  COLOR_LIST,
  NEUTRAL_INFO,
  ROLE_NAMES,
  ROLE_LIST,
  POWER_CLASS_NAMES,
  POWER_CLASS_LIST,
  type ColorInfo,
} from './vocabulary.js';
